apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: edcilo
  name: edcilo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: users-svc
                port:
                  number: 80
