apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: mongodb-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: mongodb
    nodePort: 30001
    protocol: TCP
  selector:
    app: mongodb
