apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: redis-svc
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: redis
    nodePort: 30637
    protocol: TCP
  selector:
    app: redis
