apiVersion: v1
kind: ConfigMap
metadata:
  namespace: edcilo
  name: users-configmap
data:
  FLASK_ENV: production
  APP_NAME: ms_users
  APP_VERSION: '1.0.0'
  APP_TIMEZONE: America/Mexico_City
  DB_CONNECTION: psql
  DB_HOST: postgres-svc.dbs.svc.cluster.local
  DB_PORT: '5432'
  DB_DATABASE: edc_users
  DB_USER: postgres
  REDIS_HOST: redis-svc.dbs.svc.cluster.local
  REDIS_PORT: '6379'
