apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dbs
  name: mariadb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mariadb"
