apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: mariadb-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: mariadb
    nodePort: 30336
    protocol: TCP
  selector:
    app: mariadb
