apiVersion: v1
kind: Service
metadata:
  namespace: dbs
  name: postgres-svc
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: postgres
    nodePort: 30543
    protocol: TCP
  selector:
    app: postgres
